services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: sqlserver_user_api
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=developerdaviddatabase1234!
        ports:
            - '1433:1433'
        volumes:
            - sqldata:/var/opt/mssql

volumes:
    sqldata:
